-- 코드를 입력하세요
SELECT p.PRODUCT_CODE, SUM(p.PRICE * o.SALES_AMOUNT) as SALES
FROM PRODUCT p inner JOIN OFFLINE_SALE o on p.PRODUCT_ID = o.PRODUCT_ID
GROUP BY PRODUCT_CODE
ORDER BY SALES DESC, PRODUCT_CODE ASC
