-- 코드를 작성해주세요
SELECT ID, FISH_NAME, LENGTH
FROM FISH_INFO A JOIN FISH_NAME_INFO B ON A.FISH_TYPE = B.FISH_TYPE
WHERE LENGTH IN (
    SELECT MAX(LENGTH)
    FROM FISH_INFO
    GROUP BY FISH_TYPE = A.FISH_TYPE
)
ORDER BY ID ASC