-- 코드를 입력하세요
SELECT w.TITLE, w.BOARD_ID, r.REPLY_ID, r.WRITER_ID, r.CONTENTS, DATE_FORMAT(r.CREATED_DATE, '%Y-%m-%d') as CREATED_DATE
FROM USED_GOODS_BOARD w inner JOIN USED_GOODS_REPLY r on w.BOARD_ID = r.BOARD_ID
WHERE DATE_FORMAT(w.CREATED_DATE, '%Y-%m') = '2022-10'
ORDER BY CREATED_DATE ASC, TITLE ASC